# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'MySonarCloud'
    organization: 'jhmohrbachersonarcloud'
    scannerMode: 'MSBuild'
    projectKey: 'jhmohrbacher'
    projectName: 'jhmohrbacherproject1'
    extraProperties: |
      sonar.exclusions=**/lib/**
      sonar.branch.name=$(Build.SourceBranchName)
      sonar.cs.opencover.reportsPaths=$(Build.SourcesDirectory)/**/coverage.opencover.xml
      sonar.cs.vstest.reportsPaths=$(Agent.TempDirectory)/*.trx

# three different ways to solve the initial problem

# - script:
#     cd RestaurantReviews
#     dotnet build --configuration $(buildConfiguration)
#   displayName: 'dotnet build $(buildConfiguration)'

# - script: dotnet build RestaurantReviews --configuration $(buildConfiguration)
#   displayName: 'dotnet build $(buildConfiguration)'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  workingDirectory: ./JosephProject1

# - script: dotnet test
#   displayName: dotnet test
#   workingDirectory: RestaurantReviews

# a task can encapsulate some useful logic so we don't have to
# write it all out in script step...
# in this case, this task is both running tests and publishing the results
# to the build itself
- task: DotNetCoreCLI@2
  displayName: dotnet test
  inputs:
    command: 'test'
    projects: './JosephProject1'
    arguments: '--configuration $(BuildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=opencover --logger trx'
    nobuild: true

- script: |
    dotnet tool install -g dotnet-reportgenerator-globaltool
    reportgenerator "-reports:$(Build.SourcesDirectory)/**/coverage.opencover.xml" "-targetdir:$(Build.SourcesDirectory)/CodeCoverage" "-reporttypes:HtmlInline_AzurePipelines;Cobertura"
  displayName: Create Code Coverage Report

- task: PublishCodeCoverageResults@1
  displayName: 'Publish Code Coverage'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(Build.SourcesDirectory)/CodeCoverage/Cobertura.xml'
    reportDirectory: '$(Build.SourcesDirectory)/CodeCoverage'


# - task: PublishCodeCoverageResults@1
#   displayName: Publish code coverage
#   inputs:
#     codeCoverageTool: 'Cobertura'
#     summaryFileLocation: '$(Agent.TempDirectory)/*/coverage.cobertura.xml'

- task: SonarCloudAnalyze@1
  displayName: Run Sonarcloud
  continueOnError: false

- task: SonarCloudPublish@1
  displayName: Publish sonacloud
  continueOnError: false

- task: DotNetCoreCLI@2
  displayName: dotnet publish + zip
  inputs:
    command: 'publish'
    arguments: --configuration $(buildConfiguration)
    publishWebProjects: true
    zipAfterPublish: true

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Free Trial(57f36946-3b0f-479e-8040-a30c435a39d3)'
    appType: 'webApp'
    WebAppName: 'project1joseph'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'