# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'AzureBuild'
    organization: 'jhmohrbachersonarcloud'
    scannerMode: 'MSBuild'
    projectKey: 'jhmohrbacher'
    projectName: 'jhmohrbacherproject1'
    extraProperties: |
      sonar.exclusions=**/lib/**

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  workingDirectory: ./JosephProject1

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: './JosephProject1'
    arguments: '--configuration $(buildConfiguration) --collect "Code Coverage"'

- task: SonarCloudAnalyze@1

- task: DotNetCoreCLI@2
  displayName: dotnet publish + zip
  inputs:
    command: 'publish'
    publishWebProjects: true
    zipAfterPublish: true

- task: SonarCloudPublish@1

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Free Trial(57f36946-3b0f-479e-8040-a30c435a39d3)'
    appType: 'webApp'
    WebAppName: 'project1joseph'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'